import torch
import numpy as np

# ---------------------------------------------------------
# 1. LOAD YOUR TRAINED PYTORCH MODEL OR CHECKPOINT
# ---------------------------------------------------------
# Replace 'qlim_nav_model.pt' with the exact path to your trained file
checkpoint_path = "D:\Projects\AIAA-QLIM\qlim_nav_model.pt"

try:
    # Load state_dict (handles both full models and weights-only saves)
    state_dict = torch.load(checkpoint_path, map_location=torch.device('cpu'))
    if 'state_dict' in state_dict:
        state_dict = state_dict['state_dict']
    print(f"Successfully loaded checkpoint: {checkpoint_path}")
except Exception as e:
    print(f"Error loading checkpoint: {e}")
    print("Please ensure your .pt file is in this folder or update checkpoint_path.")
    exit(1)

# ---------------------------------------------------------
# 2. HELPER FUNCTION TO FORMAT MATRICES INTO C++ ARRAYS
# ---------------------------------------------------------
def format_cpp_array(name, tensor):
    array = tensor.detach().cpu().numpy()
    shape = array.shape
    
    # Flatten array for simple static continuous memory formatting
    flat_array = array.flatten()
    cpp_str = f"// Shape: {list(shape)}\n"
    cpp_str += f"inline const float {name}[{flat_array.size}] = {{\n    "
    
    # Join values with commas, wrapping lines for readability
    entries = [f"{x:.8f}f" for x in flat_array]
    for i in range(0, len(entries), 8):
        cpp_str += ", ".join(entries[i:i+8])
        if i + 8 < len(entries):
            cpp_str += ",\n    "
            
    cpp_str += "\n};\n\n"
    return cpp_str

# ---------------------------------------------------------
# 3. GENERATE THE HEADER CONTENT BY MATCHING BLUEPRINT KEYS
# ---------------------------------------------------------
header_content = """#ifndef MODEL_WEIGHTS_H
#define MODEL_WEIGHTS_H

// =====================================================================
#include <Eigen/Dense>

// This file was automatically generated by export_weights.py
// It maps trained PyTorch Geometric parameters directly to static C++ memory
// =====================================================================

"""

# Map your specific PyG keys to our locked dense layout variables
# NOTE: If your PyG layer names vary, update the keys on the left below
weight_mapping = {
    "W_gcn1": "convs.0.lin.weight",
    "b_gcn1": "convs.0.bias",
    "W_gcn2": "convs.1.lin.weight",
    "b_gcn2": "convs.1.bias",
    "W_gcn3": "convs.2.lin.weight",
    "b_gcn3": "convs.2.bias",
    "W_lin1": "node_head.0.weight",
    "b_lin1": "node_head.0.bias",
    "W_lin2": "node_head.2.weight",
    "b_lin2": "node_head.2.bias"
}

print("\nExtracting tensor layers...")
for cpp_name, pytorch_key in weight_mapping.items():
    if pytorch_key in state_dict:
        header_content += format_cpp_array(cpp_name, state_dict[pytorch_key])
        print(f" -> Exported {pytorch_key} as {cpp_name} {list(state_dict[pytorch_key].shape)}")
    else:
        print(f" [WARNING] Key '{pytorch_key}' not found in state_dict.")

header_content += "#endif // MODEL_WEIGHTS_H\n"

# ---------------------------------------------------------
# 4. WRITE THE REWRITE HEADER FILE TO DISK
# ---------------------------------------------------------
with open("model_weights.h", "w") as f:
    f.write(header_content)

print("\nSuccess! 'model_weights.h' has been generated in your workspace folder.")